---
name: Go build
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install dependencies
        run: |
          go get -u github.com/go-telegram-bot-api/telegram-bot-api/v5
          go get -u github.com/jinzhu/configor
      - name: Build
        run: go build -ldflags "-s -w" -v cmd/main/main.go
